name: Run API Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        env:
          MONGO_INITDB_ROOT_USERNAME: username
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh admin -u username -p password --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGO_URI: mongodb://username:password@localhost:27017/gallery?authSource=admin
      MONGO_TLS: false
      JWT_SECRET_KEY: test-secret-key

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 27017; then
              echo "MongoDB is ready"; break
            fi
            echo "Waiting for MongoDB…"
            sleep 1
            [ "$i" -eq 30 ] && { echo "MongoDB did not start"; exit 1; }
          done

      - name: Run tests
        run: |
          pytest -q -s
